export const FETCH_TABLE_START = 'FETCH_TABLE_START'
export const FETCH_TABLE_SUCCESS = 'FETCH_TABLE_SUCCESS'
export const FETCH_TABLE_ERROR = 'FETCH_TABLE_ERROR'
export const CHANGE_TABLE = 'CHANGE_TABLE'
